### Numpy basics

In [3]:
import numpy as np

1\. Find the row, column and overall means for the following matrix:

```python
m = np.arange(12).reshape((3,4))
```

In [5]:
m = np.arange(12).reshape((3,4))
print (m)

m_row = m.mean(axis=1)
print(m_row)

m_col = m.mean(axis=0)
print(m_col)

m_all = m.mean()
print(m_all)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[1.5 5.5 9.5]
[4. 5. 6. 7.]
5.5


2\. Find the outer product of the following two vecotrs

```python
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
```

Do this in the following ways:

   * Using the function outer in numpy
   * Using a nested for loop or list comprehension
   * Using numpy broadcasting operatoins


In [9]:
u = np.array([1,3,5,7])
v = np.array([2,4,6,8])
print('Outer product : \n', np.outer(u,v))

Outer product : 
 [[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [11]:
outer = np.array([[ui * vj for vj in v] for ui in u])
print(outer)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


In [27]:
out_broad = np.tile(u[:,None],(1,len(u)))*np.tile(v,(len(v),1))
print(out_broad)

[[ 2  4  6  8]
 [ 6 12 18 24]
 [10 20 30 40]
 [14 28 42 56]]


3\. Create a 10 by 6 matrix of random uniform numbers. Set all rows with any entry less than 0.1 to be zero

Hint: Use the following numpy functions - np.random.random, np.any as well as Boolean indexing and the axis argument.

In [67]:
m = np.random.random((10, 6))
m[(m < 0.1).any(axis=1)] = 0

print(m)

[[0.15762147 0.44997467 0.18848624 0.47512191 0.35449265 0.91605122]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4\. Use np.linspace to create an array of 100 numbers between 0 and 2π (includsive).

  * Extract every 10th element using slice notation
  * Reverse the array using slice notation
  * Extract elements where the absolute difference between the sine and cosine functions evaluated at that element is less than 0.1
  * Make a plot showing the sin and cos functions and indicate where they are close

In [111]:
ex_4 = np.linspace(0, 10*np.pi, 100)
print('1.',ex_4,'\n')

tenth = ex_4[::10]
print('2.',tenth,'\n')

rev = ex_4[::-1]
print('3.',rev)

1. [ 0.          0.31733259  0.63466518  0.95199777  1.26933037  1.58666296
  1.90399555  2.22132814  2.53866073  2.85599332  3.17332591  3.4906585
  3.8079911   4.12532369  4.44265628  4.75998887  5.07732146  5.39465405
  5.71198664  6.02931923  6.34665183  6.66398442  6.98131701  7.2986496
  7.61598219  7.93331478  8.25064737  8.56797996  8.88531256  9.20264515
  9.51997774  9.83731033 10.15464292 10.47197551 10.7893081  11.10664069
 11.42397329 11.74130588 12.05863847 12.37597106 12.69330365 13.01063624
 13.32796883 13.64530142 13.96263402 14.27996661 14.5972992  14.91463179
 15.23196438 15.54929697 15.86662956 16.18396215 16.50129475 16.81862734
 17.13595993 17.45329252 17.77062511 18.0879577  18.40529029 18.72262289
 19.03995548 19.35728807 19.67462066 19.99195325 20.30928584 20.62661843
 20.94395102 21.26128362 21.57861621 21.8959488  22.21328139 22.53061398
 22.84794657 23.16527916 23.48261175 23.79994435 24.11727694 24.43460953
 24.75194212 25.06927471 25.3866073  25.70393989 2

In [5]:
import matplotlib.pyplot as plt

sen_x = np.sin(ex_4)

plt.plot(ex_4,sen_x,label='sen(x)')
plt.plot(ex_4,np.cos(ex_4),label='cos(x)')

#define a limit to be 'close'
lim_close = np.abs(sen_x-np.cos(ex_4))<=0.05
plt.scatter(ex_4[lim_close], sen_x[lim_close])

NameError: name 'ex_4' is not defined

5\. Create a matrix that shows the 10 by 10 multiplication table.

 * Find the trace of the matrix
 * Extract the anto-diagonal (this should be ```array([10, 18, 24, 28, 30, 30, 28, 24, 18, 10])```)
 * Extract the diagnoal offset by 1 upwards (this should be ```array([ 2,  6, 12, 20, 30, 42, 56, 72, 90])```)

In [121]:
i = np.arange(1,11)
M = np.outer(i,i)
trace = np.trace(M)
print(i,'\n',M,'\n','trace = ', trace)

[ 1  2  3  4  5  6  7  8  9 10] 
 [[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]] 
 trace =  385


In [129]:
dig_test = np.fliplr(M).diagonal()
diag_up = np.diagonal(M, offset=1)
print(dig_test,'\n',diag_up)


[10 18 24 28 30 30 28 24 18 10] 
 [ 2  6 12 20 30 42 56 72 90]


6\. Use broadcasting to create a grid of distances

Route 66 crosses the following cities in the US: Chicago, Springfield, Saint-Louis, Tulsa, Oklahoma City, Amarillo, Santa Fe, Albuquerque, Flagstaff, Los Angeles
The corresponding positions in miles are: 0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448

  * Construct a 2D grid of distances among each city along Route 66
  * Convert that in km (those savages...)

In [135]:
cities = ['Chicago', 'Springfield', 'Saint-Louis', 'Tulsa', 'Oklahoma City', 'Amarillo', 'Santa Fe', 'Albuquerque','Flagstaff', 'Los Angeles']
miles = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544, 1913, 2448])

In [139]:
route_66 = np.abs(np.tile(miles[:,None],(1,len(miles))) - np.tile(miles,(len(miles),1)))
print(route_66)

[[   0  198  303  736  871 1175 1475 1544 1913 2448]
 [ 198    0  105  538  673  977 1277 1346 1715 2250]
 [ 303  105    0  433  568  872 1172 1241 1610 2145]
 [ 736  538  433    0  135  439  739  808 1177 1712]
 [ 871  673  568  135    0  304  604  673 1042 1577]
 [1175  977  872  439  304    0  300  369  738 1273]
 [1475 1277 1172  739  604  300    0   69  438  973]
 [1544 1346 1241  808  673  369   69    0  369  904]
 [1913 1715 1610 1177 1042  738  438  369    0  535]
 [2448 2250 2145 1712 1577 1273  973  904  535    0]]


In [143]:
route_km = print(miles*1.6)

[   0.   316.8  484.8 1177.6 1393.6 1880.  2360.  2470.4 3060.8 3916.8]


7\. Prime numbers sieve: compute the prime numbers in the 0-N (N=99 to start with) range with a sieve (mask).
  * Constract a shape (100,) boolean array, the mask
  * Identify the multiples of each number starting from 2 and set accordingly the corresponding mask element
  * Apply the mask to obtain an array of ordered prime numbers
  * Check the performances (timeit); how does it scale with N?
  * Implement the optimization suggested in the [sieve of Eratosthenes](https://en.wikipedia.org/wiki/Sieve_of_Eratosthenes)

In [23]:
N = 99
#define the mask - he said shape 100 (N+1) and boolean (dtype)
mask = np.ones(N+1,dtype=bool)
mask[0] = False #0 não é prime
mask[1] = False #1 não é prime

for i in range(2,N+1):
    if mask[i]: #avaliando 'candidatos' a prime, então os multimos n serão prime
        mask[2*i::i] = False

print(mask)
#primes = np.arange(N+1) cria um array de 0 a 99 - numeros que querem ser avaliados; [mask] aplica a mask e seleeciona somente o que é True
primes = np.arange(N+1)[mask]
print(primes)

[False False  True  True False  True False  True False False False  True
 False  True False False False  True False  True False False False  True
 False False False False False  True False  True False False False False
 False  True False False False  True False  True False False False  True
 False False False False False  True False False False False False  True
 False  True False False False False False  True False False False  True
 False  True False False False False False  True False False False  True
 False False False False False  True False False False False False False
 False  True False False]
[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [27]:
import timeit

def sieve_basic(N):
    mask = np.ones(N+1, dtype=bool)
    mask[:2] = False
    for i in range(2, N+1):
        if mask[i]:
            mask[2*i::i] = False
    return np.arange(N+1)[mask]

for N in [10_000, 100_000, 1_000_000]:
    t = timeit.timeit(lambda: sieve_basic(N), number=3)
    print('for N iterations', N, 'Performance time', t)


for N iterations 10000 Performance time 0.011493500001961365
for N iterations 100000 Performance time 0.050163900006737094
for N iterations 1000000 Performance time 0.349446899999748


**N.B. the following exercises are meant to be solved only if you are familiar with the numpy random library. If not you can skip them (postponed for one of the next exercise sessions)**


8\. Diffusion using random walk

Consider a simple random walk process: at each step in time, a walker jumps right or left (+1 or -1) with equal probability. The goal is to find the typical distance from the origin of a random walker after a given amount of time. 
To do that, let's simulate many walkers and create a 2D array with each walker as a raw and the actual time evolution as columns

  * Take 1000 walkers and let them walk for 200 steps
  * Use randint to create a 2D array of size walkers x steps with values -1 or 1
  * Build the actual walking distances for each walker (i.e. another 2D array "summing on each raw")
  * Take the square of that 2D array (elementwise)
  * Compute the mean of the squared distances at each step (i.e. the mean along the columns)
  * Plot the average distances (sqrt(distance\*\*2)) as a function of time (step)
  
Did you get what you expected?

9\. Analyze a data file 
  * Download the population of hares, lynxes and carrots at the beginning of the last century.
    ```python
    ! wget https://www.dropbox.com/s/3vigxoqayo389uc/populations.txt
    ```

  * Check the content by looking within the file
  * Load the data (use an appropriate numpy method) into a 2D array
  * Create arrays out of the columns, the arrays being (in order): *year*, *hares*, *lynxes*, *carrots* 
  * Plot the 3 populations over the years
  * Compute the main statistical properties of the dataset (mean, std, correlations, etc.)
  * Which species has the highest population each year?

Do you feel there is some evident correlation here? [Studies](https://www.enr.gov.nt.ca/en/services/lynx/lynx-snowshoe-hare-cycle) tend to believe so.